language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
env:
  - REDIS_VERSION=5.0.5
  - REDIS_VERSION=4.0.14
  - REDIS_VERSION=3.2.13
  - REDIS_VERSION=2.8.24
cache:
  directories:
  - redis-$REDIS_VERSION
install:
  - test -e redis-$REDIS_VERSION/src/redis-server || ( wget https://github.com/antirez/redis/archive/$REDIS_VERSION.tar.gz && tar xzf $REDIS_VERSION.tar.gz && make -C redis-$REDIS_VERSION )
  - cpanm -L extlib --quiet --installdeps --notest .
script:
  - export PATH=$PWD/redis-$REDIS_VERSION/src:$PATH
  - export PERL5LIB=$PWD/extlib/lib/perl5:$PERL5LIB
  - redis-server --version
  - perl Build.PL
  - prove -lv t
sudo: false
